### ISSUE TITLE
Why there is no ANY handler

### ISSUE THREAD

**Issue by ysaakpr** [naoina/denco#4]
You are provided handler for POST PUT HEAD methods, Why there is no handler registration enabled without  method type?

For example

Any request on /proxy/*path should need to be handled by a handler.. How can I use this library ?? Am I missing something ??

**Comment by naoina** [comment]
@ysaakpr 

There is no way to register a handler to several methods. This is by design.
So if you want to register a handler to several methods, you should register the handler to the same URL for each method.

```go
func User(w http.ResponseWriter, r *http.Request, params denco.Params) {
    fmt.Fprintf(w, "Hello %s!\n", params.Get("name"))
}

mux.Build([]denco.Handler{
    mux.GET("/user/:name", User),
    mux.POST("/user/:name", User),
})
```

Or pull-request welcome!
